### PR TITLE
Merge this.

### PR DESCRIPTION
**Pull request by ttriche**
It'll track the various fixes as they go in :-)

### CODE REVIEW

**Comment by arcolombo** [comment]
thank you again very much Dr. Triche

**Comment by ttriche** [comment]
It's clean now.  Vignette next.  I decided to stick with Voom for the time being after talking to Kwasi.

**Comment by ttriche** [comment]
Starting to clean up and add comments in gene-wise analysis function

**Comment by arcolombo** [comment]
pulling into the container. thank you very much

**Comment by ttriche** [comment]
Merge can happen once annotation, genewise analysis is ready

**Comment by ttriche** [comment]
Goddamnit this is like pouring my own drink.  I feel like a savage

**Pull request merged**
