### PR TITLE
Adding TRAVIS support;  runs three tests Vignettes

### PR DESCRIPTION
**Pull request by arcolombo**
Hi.  So I ran the build on master branch, and it completed. takes about 30 minutes or so.  has the update .travis.yml and 3 vignettes.  This works on my end and could use some testing. 

this could be expanded in a number of ways... but I'd like to see it work first on the RL~master branch.

### CODE REVIEW

**Comment by arcolombo** [comment]
awesome the TRAVIS runs auto on the PR.  this may be great.

**Comment by arcolombo** [comment]
working on getting the checks to pass.  So I've added the travis to install the arcolombo/artemis ~ master and finally have it working.  the problem with travis is that if the repo is not set up with an API account (which im' not sure how yet) you can not trigger a local build, you can only build from issuing a commit.  so this makes the history a bit bloated, I should have done this in a branch looking back.   the next step would be to merge in all of my PR after the checks pass.  then change the RamsinghLab  TRAVIS checks to pull from ramsinghlab/artemis ~ master.   this has to be done after the merge.  then the RL should be set up.
 I've added travis to the txdblite as well which seems to be okay.

the reason there was so much difficulty is because unbeknowst to me the TRAVIS team made the r-travis software native, so the syntax completely changed.   this took a minute.  probably need to sign up for their newsletter.

**Comment by arcolombo** [comment]
TRAVIS passed.  ready to merge.

**Comment by ttriche** [comment]
Awesome.  Let me find a computer so I can LGTM this. 

--t

**Comment by arcolombo** [comment]
the TRAVIS passed after the merge.  now to switch up the travis to build off of Ramsinghlab ~master.

**Pull request merged**
