### PR TITLE
enormous speedups for collapsing TPM/counts by TSS/gene; fix for TPM calculation.

### PR DESCRIPTION
**Pull request by ttriche**
Also a few fixes to work with bioc-devel (rowRanges() moved from GenomicRanges to SummarizedExperiment).

### CODE REVIEW

**Comment by ttriche** [comment]
Prior to these changes, collapsing transcripts for a 445-sample aggregate of TCGA and TARGET RNAseq data took numerous hours (when it completed at all).  Now it takes under a minute.

**Comment by arcolombo** [comment]
travis is running, if it passes, I will have to revise the basespace app

**Comment by ttriche** [comment]
there's more, I think I may have found a bug with TPM calculations* and I
want to change the default to NOT summarizing bootstraps.  Hold tight

(*) Does not affect any of the sHSPC analyses as far as I can tell, but may
be worth rerunning anything that generates plots from TPM just in case.  I
have 445 samples' worth of hdf5 files to reprocess so I guarantee I have it
worse


--t

**Comment by arcolombo** [comment]
okay this will give me time to work on WGBS.

**Comment by ttriche** [comment]
Added fixes for TPM calculation and switched default to not summarize bootstraps. The TPM bug was a horrifying little operator precedence issue; making the grouping explicit fixes this.  Also, transcriptsBy() can now handle gene_name, gene_id, or TSS as options (the latter due to collapseByTss(kexp)).  I need this last one for downstream analyses in TARGET, TCGA, EISAI, and TACL.

All of these fixes have now been tested with 465 TARGET and TCGA runs, merged on my laptop.

**Comment by ttriche** [comment]
Added support for partial annotations, tested on TARGET + TCGA, found that there were actually 466 processed samples available.  Retested and verified per-sample TPM calculation patch as well as partial annotation on the full set of 466 samples.  Added byMad() convenience function to ease some types of exploratory analysis.  There is a bizarre error that can appear sometimes when running huge numbers of samples in parallel; the current fix is to use lapply, though eventually I will need to debug the C code in mclapply().  Please merge after Travis completes running successfully.

**Comment by ttriche** [comment]
Confirmed: TPMs exactly match those in TSV (to the limit of precision; technically the computed TPMs both from bootstraps and statically are more accurate, so any error is actually from rounding in the TSV).

**Comment by ttriche** [comment]
This is a major release, I am going to recommend regenerating figures, etc. for anything that depends on TPM.  The TPM bug was insidious (operator precedence + index recycling) but this fixes both that and a host of other issues, not least speed and memory usage for very large (500 runs) experiments.

**Comment by arcolombo** [comment]
looks like a go.

**Comment by ttriche** [comment]
Sweet.  Please consider pushing to BaseSpace ASAP.


--t

**Comment by arcolombo** [comment]
I will work on completing this ASAP, tximport is causing dependency problems after the merge.  need to update the docker container

**Comment by ttriche** [comment]
did I put tximport as a dependency?  I should remove it.  It turns out I
implemented the functions myself because Mike's were too baroque.


--t

**Comment by arcolombo** [comment]
that would help tremendously.  yes after the merge, the tximport is
required, which does not allow the container to install new artemis version
which requires it.

**Comment by ttriche** [comment]
Done.  See new pull request.


--t

**Pull request merged**
