### PR TITLE
biomaRt added a change, updated useMart() arg.  updating

### PR DESCRIPTION
**Pull request by arcolombo**
updating a bug caught from biomaRt.

ran on my end.  works OK

https://support.bioconductor.org/p/74304/

 I seriously don't get religous extremism.  On one hand you see a group that really is saying "Fuck you to modernity".  The liberal developed countries try to show its advanced methods by embracing diversity.  but how diverse can we get?  The French Prime minister says "hey, this means war."
 then in the west, we have huge marches for "subtle racism".   Snide comments, and you have a new civil rights movement in the west.    I just don't get anything anymore.

### CODE REVIEW

**Comment by arcolombo** [comment]
This pull request looks as though it has the vignette for the PCA plotting added after the bioMart bug fix.   The next pull request will have to remove bioMart all together.   The PCA vignette does successfully print out a PDF ,  currently support 2-D plotting.
The next changes for the future will have to prepare the limma output to connect with iPathwayGuide.

This change appears to include the bioMart fix , and the PCA plotting functions, and the vignette.

**Comment by arcolombo** [comment]
This PR has the singleEnd quantification ,  PCAplotting , indexKallisto with specific kmer size, and recent changes merged from timothy triche regarding arbitrary fasta trnx support.

**Comment by arcolombo** [comment]
there needs to be changes to pairFastqFiles,  and testing of the runKallisto   singleEnd,  pseudoBam parameters...  the pull request of 12/18  has edits to runKallisto  ifelse()  arguments....

**Comment by ttriche** [comment]
Ok I'll look to 

--t

**Comment by arcolombo** [comment]
My script seems to work it seems to pair up the read ones and read twos successfully. My pull request is getting quite large it seems to work on my end.

**Comment by ttriche** [comment]
I'll try and squash/merge it 

Sorry for the delay

--t

**Comment by arcolombo** [comment]
the pseudobam won't included in the LFS first run... so slow.

**Comment by ttriche** [comment]
Ok I guess it's good that we default it to off :-)

--t

**Pull request merged**
