### PR TITLE
adding saveArtemisPlots, and formatResults

### PR DESCRIPTION
**Pull request by arcolombo**
I just ran through a test and was able to reproduce formatResults.R and was able to generate plots from genWiseAnalysis.R     these two functions should be implemented into the package for operational testing

### CODE REVIEW

**Comment by arcolombo** [comment]
this pull also has erccAnalysis.r

**Comment by ttriche** [comment]
Merging, will reimplement RangedSummarizedExperiment support... from 0.1.99 forward the package is ONLY tested with bioc-devel... there's just no point supporting -release when we will never release it against the pre-RangedSummarizedExperiment code.  

Also, the code duplication in formatResults is unnecessary -- it will fail if res is not present because the design matrix is not an argument to formatResults anyways.  Without a design matrix, there can be no results.

The primary documentation for the NS analysis really ought to be the vignette, it is a step backwards to export everything out of Artemis when the entire package is designed around a heavily documented and containerized workflow...

**Comment by arcolombo** [comment]
we can discuss on to have the best documentation from within the R builds
of artemis.  you are right, why do it the hard way ?

**Comment by ttriche** [comment]
Also it is a hard requirement for BioC submission. It's unavoidable; biting the bullet early saves pain later

--t

**Pull request merged**
