### PR TITLE
Adding collapseTpmBundles()  ,  roxygenize2  didn't process the .Rmd  however

### PR DESCRIPTION
**Pull request by arcolombo**
Hi.
 this is for review, and testing only.  The bundled_tpm.RData object was created by this function, and adding onto RNA-Seq dropbox.  It seems to work, and is very simple.    this is created to create a conversation ,and merge any discrepancies between branches.    

 Thank you again

### CODE REVIEW

**Comment by ttriche** [comment]
reminder: when you open a pull request it will try to pull all changes in
your branch.  This may or may not be what you want...


Statistics is the grammar of science.
Karl Pearson <http://en.wikipedia.org/wiki/The_Grammar_of_Science>

**Comment by arcolombo** [comment]
I've re-synced my remote , it shows 4 commits ahead of RamsinghLab.  This hopefully solves unneeded commits when creating a pull request.

**Comment by arcolombo** [comment]
I think this should be closed.

**Comment by ttriche** [comment]
Let me take a quick look so that my proposed commit train doesn't run off the rails

--t

**Comment by arcolombo** [comment]
this should be closed because this used the collapseTpmBundles()  outdated.

**Comment by ttriche** [comment]
You are right, my mistake 

--t

**Pull request closed without merging**
